{% set name = "dvue" %}
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set version = environ.get('VERSION', pyproject.get('tool', {}).get('setuptools_scm', {}).get('fallback_version', '0.0.0')) %}
{% set project = pyproject['project'] %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ version }}"

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -vv .
  noarch: python
  number: 0
  {% if project.get('scripts') %}
  entry_points:
    {% for script_name, reference in project['scripts'].items() %}
    - {{ script_name }} = {{ reference }}
    {% endfor %}
  {% endif %}
requirements:
  build:
    - python

  host:
    - python
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python
    {% for dep in project['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}


test:
  imports:
    - dvue
  requires:
    - python
  commands:
    - python -c "from dvue import __version__; print(__version__)"
    {% if project.get('scripts') %}
    {% for script_name in project['scripts'] %}
    - {{ script_name }} --help
    {% endfor %}
    {% endif %}
about:
  home: "https://github.com/CADWRDeltaModeling/dvue"
  license: "MIT"
  license_file: LICENSE
  summary: "Data Visualization User interface and Editor"
