{% set name = "dvue" %}
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set version = VERSION %}
{% set project = pyproject['project'] %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ version }}"

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -vv .
  noarch: python
  number: 0
  entry_points:
    {% for name, reference in project['scripts'].items() %}
    - {{ name }} = {{ reference }}
    {% endfor %}
requirements:
  build:
    - python

  host:
    - python
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python
    {% for dep in project['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}


test:
  imports:
    - dvue
  source_files:
    - tests
  requires:
    {% for dep in project['optional-dependencies']['dev'] %}
    - {{ dep.lower() }}
    {% endfor %}
  commands:
    - pytest
    {% for name in project['scripts'] %}
    - {{ name }}
    {% endfor %}
    - python -c "from dvue import __version__; assert __version__ == \"{{ version }}\"
about:
  home: "https://github.com/CADWRDeltaModeling/dvue"
  license: {{ pyproject.get('license') }}
  license_file: LICENSE
  summary: "Data Visualization User interface and Editor"
